version: "3"
services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword
      MYSQL_DATABASE: movies
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db-container:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-container:
